services:
  api:
    extends:
      file: docker-compose-base.yml
      service: api
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    hostname: api-search
    container_name: api-search
    restart: on-failure
    privileged: true
    environment:
      # This puts Elasticsearch into development mode, which skips bootstrap checks
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      logger.level: 'ERROR'
      xpack.security.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./../elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
