"""Add ai_score to keep track of visitor feedback about using AI in museums

Revision ID: 7a875ffc6269
Revises: 
Create Date: 2025-07-08 06:32:51.264092

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7a875ffc6269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###
    # Set existing null ai_score values to 0
    op.execute("UPDATE suggestion SET ai_score = 0 WHERE ai_score IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suggestion', schema=None) as batch_op:
        batch_op.drop_column('ai_score')
    # ### end Alembic commands ###
