apiVersion: v1
kind: Service
metadata:
  name: xos-api-svc
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: acmi-api-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xos-api
  labels:
    app: acmi-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: acmi-api-app
  template:
    metadata:
      labels:
        app: acmi-api-app
    spec:
      containers:
      - name: flask
        image: acmilabs/acmi-api:BUILD_NUMBER
        ports:
          - containerPort: 8081
        args: ['scripts/entrypoint.sh']
        command:
          - scripts/entrypoint.sh
        readinessProbe:
          httpGet:
            path: /
            port: 8081
            httpHeaders:
              - name: Host
                value: local.acmi.net.au
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: 250Mi
            cpu: 200m
          limits:
            memory: 1000Mi
            cpu: 1000m
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: AWS_ACCESS_KEY_ID
                name: amazon-s3-creds-xos-api
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: AWS_SECRET_ACCESS_KEY
                name: amazon-s3-creds-xos-api
          - name: AWS_STORAGE_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                key: AWS_STORAGE_BUCKET_NAME
                name: amazon-s3-creds-xos-api
          - name: AWS_LOCATION
            value: "static"
          - name: GIT_EMAIL
            valueFrom:
              configMapKeyRef:
                key: GIT_EMAIL
                name: xos-api-env
          - name: GIT_NAME
            valueFrom:
              configMapKeyRef:
                key: GIT_NAME
                name: xos-api-env
          - name: CRON_UPDATER
            valueFrom:
              configMapKeyRef:
                key: CRON_UPDATER
                name: xos-api-env
          - name: SSH_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: SSH_PRIVATE_KEY
                name: api-ssh-deploy-key
          - name: SSH_KNOWN_HOSTS
            valueFrom:
              secretKeyRef:
                key: SSH_KNOWN_HOSTS
                name: api-ssh-known-hosts
          - name: ELASTICSEARCH_CLOUD_ID
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_CLOUD_ID
                name: api-search
          - name: ELASTICSEARCH_API_KEY
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_API_KEY
                name: api-search
          - name: INCLUDE_IMAGES
            valueFrom:
              configMapKeyRef:
                key: INCLUDE_IMAGES
                name: xos-api-env
          - name: INCLUDE_VIDEOS
            valueFrom:
              configMapKeyRef:
                key: INCLUDE_VIDEOS
                name: xos-api-env
          - name: INCLUDE_EXTERNAL
            valueFrom:
              configMapKeyRef:
                key: INCLUDE_EXTERNAL
                name: xos-api-env
          - name: SUGGESTIONS_DATABASE
            valueFrom:
              configMapKeyRef:
                key: SUGGESTIONS_DATABASE
                name: xos-api-env
          - name: JIRA_API_URL
            valueFrom:
              configMapKeyRef:
                key: JIRA_API_URL
                name: xos-api-env
          - name: JIRA_USERNAME
            valueFrom:
              configMapKeyRef:
                key: JIRA_USERNAME
                name: xos-api-env
          - name: JIRA_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                key: JIRA_PROJECT_ID
                name: xos-api-env
          - name: SUGGESTIONS_API_KEYS
            valueFrom:
              secretKeyRef:
                key: SUGGESTIONS_API_KEYS
                name: api-suggestions
          - name: JIRA_TOKEN
            valueFrom:
              secretKeyRef:
                key: JIRA_TOKEN
                name: api-jira
          - name: SENTRY_API
            valueFrom:
              secretKeyRef:
                key: SENTRY_API
                name: api-sentry
      imagePullSecrets:
      - name: docker-cred
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xos-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xos-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
