#!/bin/ash

if [ "$CRON_UPDATER" = "true" ]; then
    set -e
    ulimit -s 65536

    echo "Starting ACMI public API updater..."

    # Use update branch for API updates
    cd /code/
    if [ "$DRY_RUN" = "true" ]; then
        echo "DRY_RUN Not checking out main branch..."
    else
        # Update GitHub's RSA key
        ssh-keygen -R github.com
        curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts

        # Sanity check we're on the main branch and up to date
        git fetch --unshallow
        git pull origin main
        git checkout main
    fi

    # Update API
    export UPDATE_ITEMS=true
    export XOS_API_ENDPOINT=https://xos.acmi.net.au/api/
    python -u -m app.api
    export UPDATE_ITEMS=false

    # Check for git changes
    export GIT_DIFF=$(git diff | grep "app/json")
    if [ -n "$GIT_DIFF" ]; then
        echo "API updates found..."
        # Commit, and push changes
        git add app/json app/tsv
        git commit -m "Automatically generated by the API updater"
        if [ "$DRY_RUN" = "true" ]; then
            echo "DRY_RUN Not pushing changes..."
        else
            git push
        fi

        # Check diff again to confirm commit and push worked as expected
        export GIT_DIFF_AFTER_COMMIT=$(git diff app/json)
        if [ -n "$GIT_DIFF_AFTER_COMMIT" ]; then
            # Something bad happened... abort!
            echo "There are still changes in git after trying to commit/push! Aborting..."
            exit 1
        fi
    else
        echo "No API changes..."
    fi

    echo "Finished updating. 🥳"
else
    echo "Cron API updater not set to run."
fi
