#!/bin/ash

if [ "$CRON_UPDATER" = "true" ]; then
    set -e

    echo "Starting ACMI public API updater..."

    # Avoid `git: Argument list too long` when running git add on lots of files
    ulimit -s 65536

    # Setup git
    git config --global user.email "$GIT_EMAIL"
    git config --global user.name "$GIT_NAME"

    # Create deploy key for access to the acmi-api repo
    mkdir -p ~/.ssh
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    chmod 600 ~/.ssh/id_rsa

    # Use update branch for API updates
    cd /code/
    if [ "$DRY_RUN" = "true" ]; then
        echo "DRY_RUN Not checking out update branch..."
    else
        git checkout main
        git pull
        git checkout update
        git merge main
    fi

    # Update API
    DEBUG=true && UPDATE_WORKS=true && python -u -m app.api

    # Check for git changes
    export GIT_DIFF=$(git diff app/json)
    if [ -n "$GIT_DIFF" ]; then
        echo "API updates found..."
        # Commit, and push changes
        git add app/json
        git commit -m "Automatically generated by the API updater"
        if [ "$DRY_RUN" = "true" ]; then
            echo "DRY_RUN Not pushing changes to update branch..."
        else
            git push
        fi

        # Check diff again to confirm commit and push worked as expected
        export GIT_DIFF_AFTER_COMMIT=$(git diff app/json)
        if [ -n "$GIT_DIFF_AFTER_COMMIT" ]; then
            # Something bad happened... abort!
            echo "There are still changes in git after trying to commit/push! Aborting..."
            exit 1
        else
            # Merge update branch into main branch to create a staging release
            if [ "$DRY_RUN" = "true" ]; then
                echo "DRY_RUN Not merging API updates into main..."
            else
                echo "Merging API updates into main branch..."
                git checkout main
                git pull
                git merge update
                git push
            fi
        fi
    else
        echo "No API changes..."
    fi

    echo "Finished updating. 🥳"
else
    echo "Cron API updater not set to run."
fi
