#!/bin/ash

if [ "$CRON_UPDATER" = "true" ]; then
    set -e

    echo "Starting ACMI public API updater..."

    # Use update branch for API updates
    cd /code/
    if [ "$DRY_RUN" = "true" ]; then
        echo "DRY_RUN Not checking out main branch..."
    else
        git pull
        git checkout main
        # Get the repo history to avoid to following error when pushing large commits
        # error: pack-objects died of signal 9
        git fetch --unshallow
    fi

    # Update API
    export UPDATE_WORKS=true
    export XOS_API_ENDPOINT=https://xos.acmi.net.au/api/
    python -u -m app.api
    export UPDATE_WORKS=false

    # Check for git changes
    export GIT_DIFF=$(git diff | grep "app/json")
    if [ -n "$GIT_DIFF" ]; then
        echo "API updates found..."
        # Commit, and push changes
        git add app/json app/tsv 1>/proc/1/fd/1 2>/proc/1/fd/2
        git commit -m "Automatically generated by the API updater"
        if [ "$DRY_RUN" = "true" ]; then
            echo "DRY_RUN Not pushing changes..."
        else
            git push 1>/proc/1/fd/1 2>/proc/1/fd/2
        fi

        # Check diff again to confirm commit and push worked as expected
        export GIT_DIFF_AFTER_COMMIT=$(git diff app/json)
        if [ -n "$GIT_DIFF_AFTER_COMMIT" ]; then
            # Something bad happened... abort!
            echo "There are still changes in git after trying to commit/push! Aborting..."
            exit 1
        fi
    else
        echo "No API changes..."
    fi

    echo "Finished updating. 🥳"
else
    echo "Cron API updater not set to run."
fi
