name: ACMI API CI

on: [push]

jobs:
  build-and-test-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Python lint and test
      run: |
        cp config.tmpl.env config.env
        cd development && docker-compose up --build -d
    - name: Run Python lint and test
      run: docker exec api make linttest
